### ISSUE TITLE
Easing on sidebar

### ISSUE THREAD

**Issue by kieron** [Murked/vue-tailwind-admin#12]
Hey, I noticed the animation on the sidebar `transition duration-500 ease-in-out` doesn't seem to do anything- do you know why?

Thanks!

-- Edit

I just realised this isn't in the source, I have _tried_ to make it animated, failed, forgot I did it, then thought it wasn't my own failure! :-)

I will reframe this into, _how_ can I add animation in/out to the sidebar?

What I am struggling with is the fact that we keep the sidebar fixed & open on desktop, so you cant simply use `if="sideBarOpen"` to animate/hide/show etc. Curious how you would solve! :-)

**Comment by Murked** [comment]
Hi, the three classes you're using for animating the sidebar should be good from my memory, it is possible you have them on the wrong element though. You could try adding the "ease-in", "ease-out" classes in the sideBarOpen ternary check on the sidebar component. The tailwind version this source uses is kind of old now & i would make the sidebar component differently to make it work how you want it to. I plan on making a new updated version of this soon though.

**Comment by kieron** [comment]
Thank you!

I've ended up creating a separate mobile bar & desktop sidebar while keeping the content of the actual menu in a component, this has let me keep the sticky desktop bar & a toggleable and animated mobile bar. I just couldn't get it to work any other way ha!

Thanks :)

**Comment by opencoca** [comment]
Rather than have two menus I enjoy using a CSS breakpoint on the toggles.

**Comment by kieron** [comment]
@opencoca Have you got an example by any chance? :-)
