### ISSUE TITLE
Cant find the SVG icons that are used in the project

### ISSUE THREAD

**Issue by Norbertho** [Murked/vue-tailwind-admin#2]
HI, it is a great template, but can you share what SVG icon set have you used in this project, where can i find them?  I would like  to use the same in my project.

**Comment by Murked** [comment]
> HI, it is a great template, but can you share what SVG icon set have you used in this project, where can i find them? I would like to use the same in my project.

Hey, i used SVG icons from here: http://svgicons.sparkk.fr

I don't think i used only one specific set, i might have taken a couple from a few different sets.

**Comment by Norbertho** [comment]
Thanks for the answer :)

**Comment by snielsson** [comment]
Cool, I was wondering the exact same. This is really a fantastic theme. Any plans of a dark version ?

**Comment by Murked** [comment]
> Cool, I was wondering the exact same. This is really a fantastic theme. Any plans of a dark version ?

Since people are finding this one useful, i am planning on building a totally new one which will be way more advanced & using tailwind 2.0 which will incorporate dark mode.However, i don't have a time frame for when that will happen.
