### ISSUE TITLE
Vertical Scrollbar is Missing

### ISSUE THREAD

**Issue by fahmiegerton** [Murked/vue-tailwind-admin#24]
Hi, thank you very much for your template, but I have a problem. The vertical scrollbar is missing, even in demo. Is there any way to show it? Tried `overflow: auto`, `overflow: scroll` nothings work. Can you help me? thank you!.

**Comment by Murked** [comment]
Hi, it is disabled via a CSS rule in the `src/assets/css/tailwind.css` file.

You can comment out or remove this rule before rebuilding the css to bring the scrollbar back:

`body::-webkit-scrollbar {
    display: none;
}`

Thanks
